url: //rochack.org
description: RocHack is a group of hackers, engineers, builders, and friendly people who attend the University of Rochester. We love to build things that make people's lives better.
social-image: //rochack.org/static/photos/rochacks2014/0553.jpg
gems: [jekyll-sass]
